swiftmailer:
    transport:        smtp
    username:         noreply.delitdinfluence@gmail.com
    password:         WrBV3YWiJep36qoLZdH9
    host:             smtp.gmail.com
    port:             465
    encryption:       ssl
    auth-mode:        login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false